env:
  global:
    secure: egoXnKQUXc0hyP30EpoCjUiV9nCyOwNOwBrE4uDFbDMEp2oMPnAsrO7quwsxiE6QeNwIyK/cSYjcnx+fUizfLWxpld/JiwulFNkQCsnWctTx+LLtsZ3LzDffvSEF6RpR24E+KrjOqjJmaV5soCEkjs+j1VXrkbTQ9kMfkqAKh10=

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
